### ISSUE TITLE
jinclude.h:20:10: fatal error: 'jconfig.h' file not found

### ISSUE THREAD

**Issue by haglebu** [udo-munk/z80pack#116]
I wanted to MAKE the FRONTPANEL on my macOS and I get the following ERROR:

make -f Makefile.osx
g++ -c -O3 -fPIC -Wno-deprecated -U_FORTIFY_SOURCE -I/opt/X11/include -I/usr/local/include  jpeg.cpp -o jpeg.o
In file included from jpeg.cpp:8:
In file included from ./cdjpeg.h:14:
./jinclude.h:20:10: fatal error: 'jconfig.h' file not found
#include "jconfig.h"            /* auto configuration options */
         ^~~~~~~~~~~
1 error generated.
make: *** [jpeg.o] Error 1

**Comment by udo-munk** [comment]
Not an issue, you need to install jpeg, not included in OSX because of questionable license terms.
Try: brew install jpeg

**Comment by haglebu** [comment]
Thanks!
