### ISSUE TITLE
z80pack imsaisim webfrontend - hard disk (drive i)

### ISSUE THREAD

**Issue by zompiexx** [udo-munk/z80pack#119]
Hi Udo:

Firstly, thanks for all your work on such a great bit of software!

I am using the latest build (1.37 downloaded and compiled on 18/06/22). I have the webfrontend working with the Imsaisim and am using diskmap. This works fine for the floppy disks.

Is there a way to make hard disks available when using the webfrontend?

Thanks in advance,

Andy

**Comment by udo-munk** [comment]
Hi Andy,

the webfrontend was implemented by Dave, so far we did not see a way to implement hard disk changes in the webfrontend, it is a bit special.

**Comment by udo-munk** [comment]
With the latest update of the webfrontends the hard disks are visible. Cannot be changed in the running machine, same as with real physical ones.
