### ISSUE TITLE
Cromemco Web terminal connection state

### ISSUE THREAD

**Issue by udo-munk** [udo-munk/z80pack#121]
Tried the following:
Run machine with Cromix, connected first two tty's in the web GUI - input/output on both tty's works.
Telnet to port 4010 (tty 2), telnet server accepts connection, but no I/O possible, which is OK because web tty still is connected.
Disconnect TTY 2 in web GUI, now I/O possible on the telnet session.
Tried to re-connect TTY 2 in web GUI, not working, still tried to deconnect, state seems to be wrong, can't get it re-connected.

**Comment by dmcnaugh** [comment]
OK. I hadn't noticed the DTR disconnect function. Thanks. I will investigate and implement this for the web tty's.

**Comment by dmcnaugh** [comment]
I have been unable to observe the session terminating when a telnet connection closes. Maybe I am looking for the wrong thing?
I thought the **shell** process under cromix for the connected telnet session would end and the **gtty** would return. However, when I close/disconnector/terminate the telnet connection, nothing changes under cromix, and starting a new telnet session to the same port, reconnects to the same **shell** process.

Can you describe what I should see, or point me to the code in the cromemcosim that should notice the telnet session close and change the state for cromix to notice.

**Comment by udo-munk** [comment]
Issue is fixed.
