### ISSUE TITLE
Writing a virtual device for the Cromemco WDI-II hard disk controller

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#123]
I decided to try writing a virtual device for the Cromemco WDI-II hard disk controller.
- it has to emulate most but not all of the functionality of the Z80's PIO, DMA and CTC chips present on the WDI-II
- it doesn't need to implement interrupts as these weren't used

So far I have (successfully?) implemented:
- about 80% of the required PIO functionality
- the CTC's Timer0 and Timer2 in counter mode, used to count disk rotations (INDEX) and track seeks (SEEK COMPLETE)
- the DMA initialisation (register writes) and Memory-to-Memory DMA operation used by the WDI-II

As I don't have any harddisk image to begin with, I need to start with the cromix **init** program, and I noticed that the required version has been renamed to _init1127_
The good thing about _init117_ is that it tests the WDI-II hardware before starting to initialise the harddisk and this has helped me test/debug what I have written so far.

But I've run into a problem that does not seem related to my WDI-II emulation - the ZPU (CPU) speed test fails!

Output from _init1127_ is as follows:

```
# init1127
Initialize Disks version 02.84

Press:  RETURN to supply default answers
        ESCAPE to abort formatting
        CONTROL-C to abort program
Warning: INIT can destroy all disk data

Disk to initialize (devname)? hd0

Testing:
  PIO's and direction control transceivers OK
  Memory-to-memory DMA completed correctly
  Index pulses being received correctly
  Rotational speed:  6011 RPM
  ZPU clock must be set to 4MHz for correct operation of hard disk


Incorrect operation of drive or controller

Disk to initialize (devname)? 
```

As you can see, _init1127_ is happy with the emulation, but fails on its test to check the CPU speed. I am running _cromemcosim_ with the _-f4_ flag to set 4MHz operation.

Disk rotational speed appears acceptable, because the _init1127_ binary contains strings for messages about rotational speeds outside expected limits.

The only way I can think to understand how the CPU speed test is being performed is to disassemble the _init1127_ binary.

**Can you recommend a way to do this in cromix? Or do you know if the source code exists somewhere?** 

_init1127_ looks like it is written in 'C' based on the strings containing tokens like '%d' and '%s' for variable substitution.

If you have any other suggestions, please let me know.

**Comment by udo-munk** [comment]
Right, the problem is that the CPU runs instructions at full speed, until the ammount of cycles for a time period was used up, then it goes to sleep for the remaing time. So the avarage CPU speed will be correct, but short loops run much too fast.
On the CDOS disks you will find two versions of init, one works, the later one not anymore, due to such problems.
Don't know if 10us burst will work on every platform, needs to be tested, special on Windows/Cygwin.

**Comment by EtchedPixels** [comment]
3600 is all sorts of older stuff - things like CDC Hawks are 3600 and the SMD disk standard, most of the older DEC drives etc. Not sure what if anything could have been used at 4800 given the board had an IMI interface.

**Comment by dmcnaugh** [comment]
I've made the first significant milestone: I have a working 10MB harddisk under **cromix**!

```
# free
/dev/root      579 blocks     289K      296,448 bytes
/dev/hd0    18,463 blocks   9,231K    9,453,056 bytes
```

- This was created using the _newdisk_ command (cmd script) using _init1127_ for the initialisation as it is WDI-II compatible.
- Currently the storage for the harddisk is an in-memory array. This was just to keep things simple while I figured out the WDI-II I/O emulation.
- Now that I have it working functionally, I will change the storage to be file based.

**Comment by dmcnaugh** [comment]
In answer to the question of RPM, rotational speed:

I found the following note in the [RDOS 3.08 Technical Bulletin](https://deramp.com/downloads/mfe_archive/010-S100%20Computers%20and%20Boards/00-Cromemco/40-Cromemco%20Software/RDOS/Cromemco%20RDOS%2003.08%20Technical%20Bulletin%20023-9124%2019840214.pdf), page 5.
RDOS 3.08 support testing the WDI-II controller and booting from harddisk.

```
For IMI 7710, 5021, or 5018 hard disk drives, the RPM should be
3600 +/- 3%. For IMI 5007 hard disk drives, the RPM should be
4800 +/- 3%.
```

**Comment by dmcnaugh** [comment]
Now I have file based storage working, ie. harddisk images exist on the host filesystem as a fie (like for floppy disks).
- The format is simple: a collection of 512 byte blocks for 3 Heads, 354 Cylinders, 20 Sectors (the default format for the WDI-II), no headers between blocks
- I also have multiple harddisk support working, ie. the code supports _hd0_, _hd1_ & _hd2_ (a new __cromix.sys__ has to be crogen'ed to support this)
- It looks like **cromix 11.27** is only designed to support 3 harddisks with a Z80 (?)

So I can setup a system that boots to a root file system on _hd0_ and had the other 2 harddisks mounted as follows:
```
# free
/dev/root   18,379 blocks   9,189K    9,410,048 bytes
/dev/hd2    20,105 blocks  10,052K   10,293,760 bytes
/dev/hd1    19,581 blocks   9,790K   10,025,472 bytes
# mount
/dev/root        /
/dev/hd2         /hdd
/dev/hd1         /usr/home
```

Next steps: 
- RDOS 3.08 supports booting directly from a harddisk on the WDI-II, but when I try this it gets stuck in a loop (for now, a boot floppy is still required)

**Comment by udo-munk** [comment]
Very cool you got this far. On the cromix disks we have a bootblock for HD devices is included, /etc/hdboot. Probably the newdisk command installs this as boot block, question is for which HD controller it is, I don't know.

**Comment by dmcnaugh** [comment]
I have a better solution for all the timing, and so now the CPU timing has been reverted to previous (10ms burst intervals, avoiding any problems of changing this).
- The solution was to introduce a new global in _simglb.c_ as `unsigned long long T`  and accumulate `states` using `T += states;` in _sim1.c._ (also _sim1a.c_ for completeness).
- This gives a global CPU clock that only rolls over to zero infrequently.
- The WDI-II timing for disk index and sector times are then always made to appear in-sync with the CPU
- and always make it look like the CPU is at 4MHz, but you can run the CPU at any speed, including _unlimited_ (`-f0`) 
- and all the timing based tests now pass at any simulated CPU speed

Thanks for the tip about `/etc/hdboot`.
- I have verified that the `wboot` command under cromix 11.27 is writing this to the boot sector on the hard disk.
- The problem however is happening earlier: 
  - RDOS is polling for something on the correct I/O ports for the harddisk `E0h-Efh`
  - but is clearly not seeing what it expects and the boot loader code it not getting loaded or executed
- However the harddisk test code in RDOS can be successfully executed

**Comment by dmcnaugh** [comment]
First working version for both _cromix_ and _cdos_ published under PR #124 
Please see the PR #124 notes for details on specific versions, known issues, and limitations.

**Comment by udo-munk** [comment]
I have also posted about this in the Cromemco Google group, best resource to get answers about the hardware/software involved:

https://groups.google.com/g/cromemco/c/g9lzKydOcrE

**Comment by dmcnaugh** [comment]
Thanks. I have requested to join the group so that I can post there to ask questions etc...

What I am looking for now are alternate versions of the harddisk bootstrap file `/etc/hdboot`
The one on the _cromix 11.27_ disk is `Hdboot version 00.05` (you can run `version /etc/hdboot` to see this).

This one doesn't seem to work with the WDI-II. But I'll have a clearer picture if we can locate some other versions.

**Comment by udo-munk** [comment]
Some help for anyone trying to join the Cromemco Google group. When I did that a while ago it did not work. Reason was the the group owner doesn't care anymore and your join requests just will be ignored. I had some email communication with Marcus Bennet about this, he is a co-owner of the group and can add you manualy. So if the usual joinig process still doesn't work try to contact Marcus via email directly.

**Comment by dmcnaugh** [comment]
As the WDI-II implements real DMA, I would like to get the `HOLD` light working correctly during operation of the hard disk etc...

Referring to #18, I have spent some time implementing a BUS_REQ cycle for the CPU and the WDI-II.
I will post the code in a seperate PR for your consideration.
It is not quick fix - it is intended to be a full implementation of the BUS_REQ cycle for the CPU and any DMA bus master, so I offer the following notes:
- it wont affect existing devices that perform any kind of DMA: they could be modified to use the new scheme as required
- in the first implementation it wont provide bus request priority, but this could be added if/when required
- a call back function is used so that the CPU can call the new DMA bus master at the correct point in the M-cycle
- it will provide support for BYTE, BURST & CONTINUOUS modes of DMA
  - this allows the CPU M-cycle to effectively "clock" the DMA device to the next step (BYTE & BURST modes)
  - CONTINUOUS mode DMA simply ends when the DMA bus master is finished and doesn't require "clocking"
- the DMA bus master can (optionally) update the CPU clock (`T`) to accurately (?) reflect the time the DMA operation should have taken (this works for the Z80 DMA controller, and therefore also for the WDI-II) (zero if not important)
- helper functions are provided in `simfun.c` to
  - start_bus_request(), and
  - end_bus_request() (implicit for CONTINUOUS mode DMA)
  - these simplify writing devices that make bus requests, as they don't need to set individual flags/variables

**Comment by dmcnaugh** [comment]
I've spent too much time figuring out how the WDI-II works with different drive type/sizes/geometries.

- Cromemco only shipped a limited number of hard drives that worked with the WDI-II
  - IMI-7010 (~10MB, 8", 3 heads)
  - IMI-5007  (~5MB, 5", 4 heads)
  - and 2 more from the IMI-5xxx series with capacities of ~10 MB and ~20MB (?)
 - However the software drivers for RDOS/CDOS/Cromix appear to embed a drive parameter table for 8 drive types:
   - 4 of them are 8" drives
     - IMI-7010 as expected
     - a ~12MB capacity drive that cannot be selected by a connected drive
     - IMI-7020 (~20MB) can be selected by a connected drive, but never shipped by Crommeco (?)
     - IMI-7040 (~40MB) can be selected by a connected drive, but never shipped by Crommeco (?)
   - 4 of them are 5" drives
     - IMI-5007 as expected
     - 3 more of capacities ~5MB, ~10MB, ~15MB (could be wrong,  this is guess work)
- The problem for me with the 5" drives is that the command/control protocol is different to the 8" drives
- Right now I have the 3 viable 8" drive formats working, giving drive capacities of 10MB, 20MB and 40MB
- This is a game of diminishing returns:
  - There isn't much point to figuring out the 5" drive protocol as it doesn't give us more, larger drive options
  - I am inclined to stop here with support for the  3 viable 8" drive formats
- the emulation work out the drive type from the file size of the `*.hdd` file
  - so "seeding" the drive with a file of the right size with `00` contents is enough
    - 7010 - 21240 blocks of 512 = 10,874,880 bytes
    - 7020 - 38800 blocks of 512 = 19,865,600 bytes
    - 7040 - 77600 blocks of 512 = 39,731,200 bytes
    - if the file does not exist or is empty, zero/unknown length then the default is the 10MB - 7010
- There is a problem with using the 7040 (40MB) drive type 
  - while it seems to work generally
  - you cannot run `dcheck` on a disk of this size, it fails with a `Not enough memory` error because there a too many inodes to process
  - this might explain why Cromemco didn't ship a drive of this capacity for Z80 based machines with the WDI-II
  
A PR will follow shortly.

**Comment by dmcnaugh** [comment]
I continue to find problems using the 40MB disk type under _cromix_
- it can only be successfully formatted (`makfs`) and mounted as the root disk
- no other hard disks (any size) can then be mounted, any attempt causes a seg fault
- the `dcheck` issue remains even in this mostly working condition
- I think its OK under CDOS as that isn't trying to manage a complex filesystem of inodes etc...

It starts to suggest why Cromemco only configured _cromix_ (and utilities) with 3 harddisk devices  hd0, hd1 & hd2
And it doesn't appear from any brochures or manuals that I've seen that a 40MB drive was marketed for Z80 base _cromix_ 

I'll include the support for all 3 of the 8" disk models/sizes in the PR so you can play around with it and see for yourself what works and what doesn't work.

If it continues to be a problem it might be best to limit the choice to  10MB (7710) and 20MB (7720) options to avoid issues.

**Comment by EtchedPixels** [comment]
I don't know how closely traditional Unix file system layout is copied but System III and earlier were limited to 32MB in real Unix (16bit of 512 byte blocks).

**Comment by dmcnaugh** [comment]
OK, that comment about 16bits worth of 512 byte blocks got me thinking...

It appears that mounting any combination of disks where the total number of mounted blocks would exceed 2^16  causes the emulator to crash with a segmentation fault - presumably because _cromix_ is trying to do something outside of bounds that aren't checked in _cromemcosim_

The one exception is mounting a 40MB (7740) type drive as the root partition, but I'd expect this to ultimately prove to be unstable.

So the simplest solution would be to only allow 10MB drives up to a maximum of 3 - I guess this is what Cromemco did during the time of the WDI-II by only shipping 10MB and 5MB drives and configuring _cromix_ for just hd0, hd1 & hd2.

Maybe by the time of the STDC controller they found a different solution to avoid this limit in how the driver is coded, or maybe they just increased the block size.

The alternative is to allow all 3 drive sizes but provide a note that explains the working vs. non-working combinations and limitations and allow people to experiment at their own risk.

_CDOS_ is simpler because the maximum "size" allowed is managed by a limit of 512 directory entries, so having a 40MB or even a 20MB disk just isn't interesting if you can only have a maximum of 512 files in the one-and-only directory.

**Comment by EtchedPixels** [comment]
The seg fault is a bit worrying - if you can segfault it then it's potentially possible to build a trojan CP/M application that can escape the emulator and hack the host.

**Comment by udo-munk** [comment]
Yes, besides the security risk it also is unpleasent for the user. The emulations never ever should seg fault, regardless what some software does to the hardware. If the hardware emulation cannot handle some situation whe have the defined exits with error log. So this needs to be inspected and fixed, would be helpfull to know how to reproduce the seg fault.

**Comment by dmcnaugh** [comment]
To cause the seg fault
- create a hard disk file for hd1 that is one of the two larger sizes
- Start cromemcosim and boot cromix on your existing hd0 hard disk
- `init` hd1, this should work
- `makes hd1` should seg fault, if it doesn't then
- `mount` hd1 should seg fault

**Comment by udo-munk** [comment]
Unfortunately it works for me, no seg fault:

# makfs /dev/hd1
# mount /dev/hd1 hd1
# free
/dev/root   17,929 blocks   8,964K    9,179,648 bytes
/dev/hd1    36,496 blocks  18,248K   18,685,952 bytes
# 

Sometimes a bug comes up on one platform only, so have to try with some other host OS's and see if I can reproduce it.

**Comment by dmcnaugh** [comment]
OK, but my advice was untested and incomplete:

These two disks still have a total capacity < 2^16 blocks: 21240 + 38800 = 60040

So keep going and `init/makfs/mount` to add a third disk `hd2` even a 10MB (21240 blocks) type, and you should get a seg fault.

My platforms are both macOS Monterey 12.4 but one is Apple M1 and the other is Intel i5

**Comment by dmcnaugh** [comment]
Bad news: the root cause is as I suspected:
- _cromix_ is doing something out of bounds when there are too many total hard disk blocks to manage
-  it is corrupting the hard disk _unit_ value, and trying to select a hard disk that no longer corresponds with the minor device number in `/dev/hd?`
 
Good news: I found the cause of the seg fault and it was within the WDI-II emulation, so I can account for that.
- I've added bounds checking in `cromemco-wdi.c` for _unit_, _head_ & _cylinder_ preventing any further seg faults.

I haven't tested every disk combination but I find the following shows some kind of pattern:
- Working combinations are:
  - 1, 2 or 3 7710's as hd0, hd1, hd2
  - hd0 as 7710 followed by hd1 as 7720 but no hd3
  - hd0 as 7720 but no hd1 or hd2
  - hd0 as 7740 again no hd1 or hd2 - but this has the problem with `dcheck` giving an `out of memory` error 
- any other combination, either wont mount hd1 or hd2, or produces some kind of read or write error

This provides total hard disk capacity of 10, 20, 30 or 40MB. But I would have reservations about using the 7740 because of the problem indicated by `dcheck`.
So if 30MB is the maximum and that can be achieved with 3 x 7710 drives, I see no point supporting the 7720 and 7740 drive types. These were not commercially available, and maybe for good reason.

Any last input? Otherwise I will provide a PR that only provides support for the 7710 drive type and includes the bounds checking for good measure.

**Comment by udo-munk** [comment]
I was able to reproduce the problem with a second 20 MB drive. Problem is a buffer overrun somewhere in the WDI code:

Welcome to Cromix 11.27
mount /dev/hd1 hd1
mount /dev/hd2 hd2
Process 97500 stopped
* thread #1: tid = 0x154754d, 0x00007fff93f32732 libsystem_c.dylib`strlen + 18, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fff93f32732 libsystem_c.dylib`strlen + 18
libsystem_c.dylib`strlen + 18:
-> 0x7fff93f32732:  pcmpeqb (%rdi), %xmm0
   0x7fff93f32736:  pmovmskb %xmm0, %esi
   0x7fff93f3273a:  andq   $0xf, %rcx
   0x7fff93f3273e:  orq    $-0x1, %rax
(lldb) 

Looks like you found it already and fixed it.

**Comment by udo-munk** [comment]
Well, I would leave in everything implemented. It might not work with Cromix, but can be made working with other OS's like Fuzix.
On the early 16bit like UNIXes like MINIX, COHERENT ... we all the time ran into issues like that when disk capacity doubled in the next generation. Out of memory for the growing check lists, 16bit block number cannot address the full disk anymore, and so on and forth. One has to life with that or find a workarround somehow, likeley not going to happen for Cromix without sources.
