### ISSUE TITLE
Initialisation messages from the frontpanel library do not format correctly if PR #12 is applied.

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#13]
This can be fixed in a further update that moves all the frontpanel init/exit code out of simctl.c and into the correct place in the initialisation sequence i.e. init_io() and exit_io()

**Comment by udo-munk** [comment]
The front panel is no I/O device, it controls operation of the CPU's.
Patch #1 from PR#12 not applied, so problem doesn't exist.
Excluding POSIX functions from IMSAI simctl.c will be done with #ifdef's
