### ISSUE TITLE
Question about C baseline for z80asm

### ISSUE THREAD

**Issue by sneakywumpus** [udo-munk/z80pack#151]
What kind of vintage of C compilers should be able to compile z80asm?
Is it safe to assume C89 features?
For example, remove the isxdigit macro and use getopt()?

**Comment by udo-munk** [comment]
C89 is very safe to assume, I gave up compiling it on CP/M and the like long ago.
In 1987 I had promlems with getopt() on some systems, which I avoided with the isxdigit macro.
Such systems are not relevant anymore, everyone can easily use more modern systems than that, so fine with me to change this. Just try to make sure it still builds on C89 systems, from time to time I like to use the assembler on my old COHERENT systems.

**Comment by sneakywumpus** [comment]
Since the simulator already uses inline functions I'll remove the isxdigit macro from z80asm,z80core,z80sim,cpmsim, mosteksim and sim.h everywhere and also change the ctype castings from (int) to (unsigned char). I'll keep my fingers from symctl.c other than in cpmsim and mosteksim and the frontpanel, iodevices and webfrontend directory. OK?

**Comment by udo-munk** [comment]
Yes fine with me.
