### ISSUE TITLE
List new/added functionality, todo's, feature requests, work underway, etc... as new Issues

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#19]
In your first response to Issue #18, you mention:
```
 I'm willing to change my priority list and start working on this with you now, it has to be done anyway, but then other things have to wait...
```

Can I suggest we all add any ideas for new/added functionality, todo's, feature requests, work underway, etc... as new **Issues** and **label** them accordingly. With visibility of what's on peoples' lists/minds then others might decide to contribute to solving some or making additional suggestions.

**Comment by udo-munk** [comment]
Yep, will do later.
