### ISSUE TITLE
cromemco z-1 will not boot CP/M 2.2.

### ISSUE THREAD

**Issue by kazueda** [udo-munk/z80pack#259]
Dear Sir,

I am trying to boot cromix on Cromemco Z-1 emulator of z80.pack.
First I am trying to boot cpm2 but the emulator will not boot after  the "RUN" swithch was pushed.

How can I overcome this trouble. 

My circumstances are follows.
1. z80pack cloned from git repository on ubuntu22.04
2.  z80pack-1.36 on ubuntu18.04

Sincerely yours,
kazueda

**Comment by udo-munk** [comment]
First you need to switch power on. Example video that shows how to operate the machine:
https://www.youtube.com/watch?v=GUF6CBPtvtY&list=PL2MKNKU8M--FwJqUYhCmG30TvYmgEleI_

**Comment by kazueda** [comment]
Sorry for misleading.
On the panel, first I pushed PowerOn switch, then I pushed the "RUN" switch.
But my terminal will not show Bank checking process.

**Comment by kazueda** [comment]
Thank you for you video.
I can boot cromemco z-1 emulator.
[PWR ON/ PWR OFF] -> ON -> [ADDRESS-PROGRAMMED INPUT 12/4] ->  up -> [RUN/STOP] -> RUN

Sorry for my boring question.

**Comment by udo-munk** [comment]
The RDOS boot ROM is waiting for baud rate detection, you need to enter a few CR on the terminal. With 12/4 up a fixed baudrate of 9600 is used and it won't wait. Also see README in cromemcosim directory, it explains the RDOS boot options.
You are welcome, enjoy using the machine.
