### ISSUE TITLE
Where is the C compiler, how does it work?

### ISSUE THREAD

**Issue by KedalionDaimon** [udo-munk/z80pack#261]
I understand, it should be the command "cc".

But when I log into cromix_work.dsk as system, I see nothing like it, neither in /bin, nor in /cmd, nor in /usr/pkg/tools. So I assume I am missing something?

find / -name "*.h" -a -exec l -l {}

- did not find any header files, either. So where is the C compiler, and how is it to be used in a brief example? Thank you!

**Comment by udo-munk** [comment]
Are you sure you mounted cromix_work.dsk? On this disk the C compiler is installed and the commands to run it are /cmd/cc.cmd and /cmd/ccdos.cmd.
Login with user1, no password, there is a simple hello.c source to try the compiler.
And then here is a video that shows how to compile stuff: https://youtu.be/YIirQYJK52U

**Comment by udo-munk** [comment]
This is not an issue, so I will close it. Feel free to use Discussions for questions about how something works, thanks.
