### ISSUE TITLE
imsai 8080 no sound on tumbler clicks.

### ISSUE THREAD

**Issue by Selorax** [udo-munk/z80pack#262]
I don't know if it's supposed to output any sound or not, but on my setup there is no sound when I switch tumblers, neither on IMSAI, nor on Altair with front panels of latter tested both in 3D and 2D.

z80pack version is 1.37.

In comparison, https://www.s2js.com/altair/sim.html has sound, which adds a lot to the experience, even though the emulator is lacking in having no peripherals and only 256 bytes of memory, or so it seems.

**Comment by udo-munk** [comment]
No there is no sound output.

**Comment by Selorax** [comment]
@udo-munk can we make it a feature request, to add sounds? I think it's important part of front panel experience, and makes it easier to spot if you toggled the switch twice by mistake or something like that.

**Comment by udo-munk** [comment]
Sure, I'll leave this issue open, so that whoever wants can add sound for some supported platform.

**Comment by udo-munk** [comment]
Because this is not really an issue, but a missing feature I'll close this here. Instead I opened a discussions under ideas to add sound to the machines.
