### ISSUE TITLE
Add 8080 opcode table to z80asm

### ISSUE THREAD

**Issue by udo-munk** [udo-munk/z80pack#28]
Priority: low, I'm using Intel's 8080 macro cross assembler
Difficulty: easy

Add the 8080 opcode table and the same PSEUDO ops as in the Z80 table. Add new PSEUDO ops .Z80 and .8080 to switch between the instruction sets. Make .Z80 the default, that is the name of the assmbler ;-)

**Comment by sneakywumpus** [comment]
Implemented in #135

**Comment by udo-munk** [comment]
Fine with me. I just left the formatting from Didier, I guess he also won't mind.
