### ISSUE TITLE
Add .PHASE to Z80 assembler

### ISSUE THREAD

**Issue by udo-munk** [udo-munk/z80pack#29]
Priority: high
Difficulty: medium

The CP/M assemblers are not really good for developing firmware, standalon software etc. Often parts of the code need to be phased to another execution address, to be able to move code from ROM into RAM and such. Of course the necessary offset calculations can be done with expressions, but this is a workarround for the missing .PHASE pseudo-op, not very comfortable.

**Comment by sneakywumpus** [comment]
Added an implementation for this in #143
