### ISSUE TITLE
Review and fix uses of mem_base() in all machines that implement banked memory

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#34]
Priority: low
Difficulty: easy or difficult, depends on each machine memory architecture

Machines that implement banked memory and also use `mem_base()` are only looking at the first/base bank when accessing values via `mem_base()`.
This is happening now in `report_error()` (or similar) in all such machines when attempting to show the opcodes of instructions that fault with `OPTRAP*`, however, they are retrieving the bytes from the first/base bank via `mem_base()` and not the bank where the error occurred.
Possibly, uses of `mem_base()` should be replaced with macros that default to the `mem_base()` implementation for simple machines without banked memory, but that machines can selectively override to implement correct memory access for their individual memory architecture.

**Comment by udo-munk** [comment]
Fixed in all machines using banked memory. Usage of mem_base() now is reduced to the z80sim ICE only, which also is used in mossim, both not banked machines. The ICE needs to be re-written by using the memory access functions, so that it also won't work with pointers directly on the memory anymore.
