### ISSUE TITLE
Make the VIO plug-any-play in the imsaisim

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#36]
Priority: low
Difficulty: moderate,  order of events doesn't favour this, ie. memory is initialised before ROM file is loaded so how does the VIO ROM get identified?

The CP/M BIOS already looks for the 'VIO' string in ROM to enable the VIO as the `con:` device.
The imsaisim could reserve and initialise RAM/ROM for the VIO only if the VIO ROM has been loaded.
This would release those extra few KBs for CP/M.

**Comment by udo-munk** [comment]
simctl::init_io() already checked if the VIO firmware was loaded by looking at the signature bytes in the firmware. If the signature is not there we convert the ROM to RAM in the page table.
