### ISSUE TITLE
Enable headless imsaisim mode ie. runs with no CP-A attached

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#37]
Priority: low
Difficulty: easy

Might need some way to power-cycle and reset

**Comment by udo-munk** [comment]
There is the virtual hardware control port which is intended for these things. Example implementation for reset is in cpmsim, which can't be operated from a fp. If possible use the same I/O bit for a function in every machine, then one common 'bye', 'reset' ... program will do for all machines.

**Comment by udo-munk** [comment]
Done.
