### ISSUE TITLE
The cpmsim hd-tools.dsk image seems to be broken

### ISSUE THREAD

**Issue by hechtus** [udo-munk/z80pack#412]
I was trying to use the hd-tools.dsk image. When doing DIR as USER 0. Only a few files were shown:
```
64K CP/M Vers. 2.2 (Z80 CBIOS V1.2 for Z80SIM, Copyright 1988-2007 by Udo Munk)

A>i:
I>dir
I: TRACE    UTL : HIST     DOC : UNARC    DOC : Z80      DOC
I: USQ120   DOC : Z80      LIB : HIST     UTL : MACRO    LIB
I: LS       DOC
I>
```
When using the  `cpmls` command more files are shown. As I'm experiencing the same issue with another CP/M distro I suspect there is something wrong with the image file.

**Comment by udo-munk** [comment]
Nothing wrong with it, all the .com files on the disk have SYS attribute set. This is because OS's later than CP/M 2 also will look in user 0 for files with SYS attribute.

Use sdir (DRI's superdir command) to also show files with SYS attribute, that is the default.
For more options: sdir [help]
