### ISSUE TITLE
Implement a light-weight logging library

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#45]
Priority: High
Difficulty: Easy

The objective with this is to:
- Differentiate log output to the console from the TTY: (CP/M) device I/O
- Allos for (later) redirecting the log output somewhere else like a file, syslogd, or a websocket
- Use something that is all(mostly) macro pre-processing and doesn't add weight to the executable
- Use something that is simply a header file eg. `log.h` 
- Support a range of logging levels eg. ERROR, WARN, INFO, DEBUG, VERBOSE, and plain LOG
- Let the log level be set globally (and in each file individually if required) and is baked in at compile time
- Let features like colour-coding different log levels, customising the format and timestamp, be easily selected and changed by the developer

I've become use to having a library like this available from the platform on my ESP32 build, and since its under the Apache 2.0 license, I've made a simplified version that resolves everything down to `vprintf()` and is portable. I'll put it in a PR for `dev`, and there will be examples of it in use in the code I start to put up for #38 (or related).

**Comment by udo-munk** [comment]
Merged and implemented in imsaisim/srcsim, looks good.

Needs to be implemented everywhere, guess I'll need a while for that...

**Comment by udo-munk** [comment]
Note: before I forget, don't implement in front panel library, at least not yet. The version included in z80pack is the most current one, and I don't know if it is used elsewhere. The version on sourceforge is outdated, and John has no time for this due to long term commitment.

**Comment by dmcnaugh** [comment]
Take care using `LOG()` as it always produces an undecorated and unprotected output. So its equivalent to puting  a `printf()` in the code. As can be seen in cc0e431528c28ecd178e4380b4520f199ee07a92 puting a `LOG()` in when a `LOGD()` was required can lead to noise on the TTY:

**Comment by udo-munk** [comment]
That was my intention because the log looked nicer. Of course forgot that it will always print and not only the DEBUG stuff, oh well.

**Comment by dmcnaugh** [comment]
You could just move the extra `\r\n` to the end of the line above.

**Comment by dmcnaugh** [comment]
Regarding e12b3de1d95a0acb274e5e0b19c2fe110a23e088
The `__always_inline__` macro is desirable, but more important is the `__attribute__` directive.

Could you test for the version of `gcc` using
```
__GNUC__
__GNUC_MINOR__
__GNUC_PATCHLEVEL__
```
And have an alternative of this line for specific versions of the compiler?

**Comment by udo-munk** [comment]
I'll have a look at nicer formatting later, guess we first want using logging everywhere.

For gcc I have to fiddle with this with various releases currently in use on various OS's. The one causing the problem was 7.3 on Windows/Cygwin.

**Comment by udo-munk** [comment]
Everything in z80sim/iodevices is now using logging.

There are plenty printf() etc. left in sim0.c mostly for signon, not sure if these can be left or do you need to use this logging too?

**Comment by udo-munk** [comment]
Regarding __attribute__ and GCC:
Had a look at various Linux distros which gcc version is used. All < 7. So I just #ifdef __GNUC__
and use the __attribute__ without inline. Now it compiles with gcc and clang on all platforms I tried.

**Comment by udo-munk** [comment]
The Altair system is using logging now.

**Comment by udo-munk** [comment]
The cpmsim system is using logging now.
