### ISSUE TITLE
Implement a disk manager for use by floppy disk controller modules

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#48]
Available now in PR #47.
Ready to work with
- `imsai-fif.h` (integarted in the PR)
- `tarbell_fdc.h` (should be very easy to integrate)

Some work is required to support more complex disk arrays that contatin structures e.g.
- `cpmsim::iosim.c`
- `cromemco-fdc.c`

**Comment by udo-munk** [comment]
I can separate the disk array from the disk definitions, so that the disk manager always sees the same disk drive structure in all FDC's. Probably better than trying to support various more complex structures in the diskmanager.

**Comment by udo-munk** [comment]
IMSAI 8080esp kit is shipping, so implementation completed for now.
