### ISSUE TITLE
CB 37 should not be counted as Z80_UNDOC

### ISSUE THREAD

**Issue by EtchedPixels** [udo-munk/z80pack#49]
Zilog's Z280 manual explicitly says to use

ld a,#0x40
.byte CB,37
jp p, z280_cpu

to tell Z80 and Z280 apart. So it's documented undocumented, and it breaks those (rare) bits of software that try and detect a Z280 processor

See Zilog Z280tm MPU MIcroprocessors Unit Preliminary Technical Manual: Appendix A

**Comment by udo-munk** [comment]
Fixed so that this instruction never traps, thanks.
