### ISSUE TITLE
Fuzix MMU traps

### ISSUE THREAD

**Issue by EtchedPixels** [udo-munk/z80pack#5]
I find these useful for debugging Fuzix stuff.

This changes the wp_common I/O port behaviour a little so that bit 7 is set on a trap (cleared by writing the register again), and if bit 6 is set we also NMI.

Recovering from the NMI or dropping into a Z80 monitor is a shade interesting because we may have faulted trying to push stuff so have no valid return frame - but it's still useful 99% of the time.
[mem.txt](https://github.com/udo-munk/z80pack/files/1885355/mem.txt)

**Comment by udo-munk** [comment]
Thanks, added to dev.
