### ISSUE TITLE
tu-art hangs on a polled transmit when a timer is pending

### ISSUE THREAD

**Issue by EtchedPixels** [udo-munk/z80pack#63]
In the case that a timer is pending but the system is sitting in a polling interrupt disabled loop doing output the system wrongly deadlocks because the emulation keeps the transmit buffer clear bit clear until the timer has cleared.

**Comment by EtchedPixels** [comment]
[1.txt](https://github.com/udo-munk/z80pack/files/3538610/1.txt)

**Comment by udo-munk** [comment]
Thanks for the fix, comitted.
