### ISSUE TITLE
Implement a Hayes (AT) style, virtual modem (over telnet).

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#66]
I have created a working prototype of an AT command driven, telnet based virtual modem.
AT commands implemented include:
- `AT`, test AT 
- `AT?`, display basic help
- `A/`, (immediate, <cr> not required) repeat last command
- `ATH`, hangup current connection
- `ATDname:port`, make a telnet connection to 'name' on the specified port (23, default if none given) then enter *data* mode
- `+++` (with a 1 sec guard interval before and after), return to *command* mode from *data* mode
- `ATO`, (re)enter *online/data* mode

this appears to be a workable minimum set of commands to make and hangup a connection.

I currently have it implemented on the **imsaisim**,  2nd SIO on port A, but could just as easily move it to port B.

A couple of issues have surfaced:
1. something on the CP/M side is stripping bit 8 after receiving extended ASCII chars (>127) but before they are displayed. This is using KERMIT.COM on the TTY: console
  - I don't think its the simulation device code
  - It doesn't look like the CP/M BIOS would strip anyhting
  - KERMIT  is `set parity none` so it shouldn't be KERMIT
  - Could the BDOS be doing this?

2. Some UI is required (probably on the web/desktop UI) to reset the modem in the event you cannot get control back with a '+++'
3. If the modem is moved to the 2nd SIO port B, it would be useful to have BIOS support to access it on the CP/M physical device UR1:/UP1: so KERMIT.COM can see it.

I will soon post a PR to make this available in upstream Z80PACK. For now I can also provide a custom firmware for the IMSAI8080esp that replaces UART1/RS232-2 support with this virtual modem on UC1: (2nd SIO on port A).

**Comment by dmcnaugh** [comment]
I wrote my own simple assembly language program to just shift bytes as follows:
in port 02h -> out port 022h
in port 022h -> out port 02h (and port 0ffh, just to see what was flowing in) 
with the modem mapped to SIO2 channel A
was was getting all 8-bits of data transferred from the TCP/IP socket to the terminal (minicom) connect to port 02h.

So if the BIOS and BDOS aren't stripping the MSB then it must be KERMIT despite the `set parity none` setting.
 
I agree that the modem should me mapped to SIO2 channel B, although I might introduce a mechanism to allow users to configure what devices are mapped to what channel on SIO2 because I have some other virtual (desktop GUI) devices in mind eg. virtual punch tape, cassette, another serial terminal window that can't all be supported at the same time (might be time for CP/M 3.0 (Plus)

Meanwhile, I don't think generic KERMIT is the best choice for another reason: it doesn't work with UR1:/UP1:, possibly because they don't have a 'status' call in the BIOS like `TTY:` and `UC1:`

So I'm looking for a copy of QTERM  to try this with. Any pointers?

**Comment by udo-munk** [comment]
OK, all hardware then is 8bit clean.

Kermit will work with 7 data bit transfers, in the CP/M version you can't even select this.

Generic Kermit does work with whatever is assigned to the RDR:/PUN: device. Because there is no BIOS status call for reader/puncher you cannot abort the connection with CTL-C, as is the case
with the console devices. One could build a Kermit for the system, that directly uses the I/O ports.

Qterm is available here:
http://www.retroarchive.org/cpm/cdrom/CPM/QTERM/

Same as with Kermit it needs to be build for the system to use the I/O ports.

**Comment by udo-munk** [comment]
I have uploaded disk images with qterm sources, binary and documentation to the z80pack repository, so that one can work on a patch for IMSAI systems.

**Comment by udo-munk** [comment]
I've added a patched QTerm to the disk immage with communication programs. It uses Channel A of the second SIO, for using with the telnet modem you need to change the port defines (source included on the disk).

**Comment by dmcnaugh** [comment]
Thanks. This makes it much easier. Works as expected on SIO - 2A. I will patch it for SIO - 2B and test in that configuration also.

**Comment by udo-munk** [comment]
I updated the program so that you can switch between both ports with CTL-^U :)

**Comment by dmcnaugh** [comment]
I have done more work on the AT modem:

- it now and accepts incoming calls (listen, 1 at a time) with a 3 second RING cycle `AT&A`
- incoming port is currently 8023, as ports below 1024 are restricted (this could be made configurable via a register)
- supports AutoAnswer by setting register 0 to a non-zero number of RINGS to answer after
- has commands to query and change registers `ATSn?` and `ATSn=r`
- AT command help is now mapped to `AT$`
- mapped to SIO-2b

It's not perfect but it's highly functional. The only advantage of mapping it to SIO-2a would be to enable AutoAnswer and then using `stat CON:=UC1:` we could accept an incoming connection as the console!

I will test a little more and then make a PR.

**Comment by udo-munk** [comment]
Sounds good. For incoming calls one could run some BBS software on the modem port, probably more interesting that dialing into a CP/M console anyway.

**Comment by dmcnaugh** [comment]
PR #67 now ready for your consideration.

Note: the modem is 8-bit clean. But I have discovered that the virtual TTY: on the Desktop GUI is not 8-bit-clean. I have a fix and will be publishing a seperate PR that addresses that.

**Comment by udo-munk** [comment]
I have changed the BIOS so that SIO2B is assigned to UC1. Now kermit likes to talk to the modem too, and we can dial into the console.

**Comment by dmcnaugh** [comment]
I think while working with CP/M 2.2 the allocation of UC1: will be something people might like to change. 
I would like to add a mechanism to allow the I/O port assignments of SIO2A and SIO2B to be swapped. It doesn't need to be dynamic while the simulation is running, it could be set when the simulation is started. 
My preference is to use an *environment variable*. This is what all the entries in the `boot.conf` file in the ESP32 port become - just environment variables that can be queried elsewhere in the code as required.
If you are happy with this approach I will put a PR together for **z80pack**.

**Comment by udo-munk** [comment]
That is likely, yes. I thought about asking this from the BIOS, which channel to assign to the port, but the BIOS growed too large for this, only 8 Bytes left in the code segment.
One could write a CP/M program that swiches the table entries in the logical device routines, but that will need some time because it has to find the BIOS, the tables and then put the correct function addresses into those.
Using an enviroment variable is much faster to implement, so I'm happy with this too, please go ahead.
I can write such a program for swapping the ports dynamic in a running system sometime later.

**Comment by udo-munk** [comment]
I have added submit scripts (porta.sub & portb.sub) that patch the running system for UC1 = port A or B. The power of CP/M :-)

For this I needed space on the OS disk, so I have moved the DAZZLER programs to an own disk for such stuff. This one also has enough space now to add more programs.

**Comment by udo-munk** [comment]
Just implemented enough of the telnet protocol, so that a full session with the modem is possible now @ nethack.com. Can login, play adventure, zork etc.

Needs review, likely needs improvements.

**Comment by udo-munk** [comment]
@EtchedPixels

After MMU is implemented and FUZIX running on the box, of course you'll have access to the modem. I don't know if you are aware about it, I have rebuild the complete 16bit COHERENT from sources, kernel, driver and all user land. This includes MWC uucp, the 16bit version we were using before moving to Taylor uucp. I did run COH 3.2 on QEMU with serial line against Taylor UUCP running on the host and checked that it still works. This 16bit uucp implementation probably is small enough to cram into 8bit FUZIX, and that would be very cool then ;-)

**Comment by EtchedPixels** [comment]
@udo-munk I must admit UUCP wasn't top of my TODO list. Nice to know you can rebuild all of coherent from the giant dump that was made. I never tried - just used some of the utils and the like.

**Comment by udo-munk** [comment]
You can get VM's/disk images for Virtualbox, PCem, Qemu here:
https://www.autometer.de/unix4fun/coherent/index.html
The boxes are already set up as development systems with sources, the 3.2 one is complete and can install it self from sources on a second harddisk, and replicate it self again ...
The last thing I did was uucp, I also thought oh well, who would use this again. But after I had it working and uucp'ed beteen the VM's and the host I quite had some fun with this again.
Just though I'll let you know that it is there, and probably could be made working on the Z80 systems running FUZIX.

**Comment by dmcnaugh** [comment]
I see what you've done with the telnet protocol and I like it.
I have taken this as a set of requirements and reimplemented it:
- all inside the `generic-at-modem` module (moved it out of `imsai-sio2`)
- using a telnet parsing library https://github.com/seanmiddleditch/libtelnet
- have also implemented TTYPE (terminal type) negotiation. Default response in `ansi` but this can be changed using an environment variable

The reasons are 
1. to make it more flexible for future modification and additions
2. put the telnet protocol and the options implemented under control of the modem  
    - telenet protocol can be turned on/off using a modem register eg. `ATS15=1` for on, `0` for off
    - telenet protocol options can be changed using modem registers eg. `ATS16=40`, `ATS17=16` for 40 column 16 rows (NAWS)

I have it working on the ESP32 port and will soon post a PR for Z80PACK

Note, the whole modem is a state machine, clocked by polling the SIO2B status port. If the port isn't being polled, then the modem is not doing anything and might be paused in the middle of parsing and processing a tenet negotiation or interpreting an AT command including the `+++` interrupt

**Comment by udo-munk** [comment]
Would be great to have control over the telnet options via modem settings.
I refused to negotiate terminal type because often using the wrong type makes things worse. Without agreed terminal type the other end usually assumes a dumb terminal. If the terminal type can be configured somehow, one still can set it to dumb to avoid problems, if any.
Looking forward to the PR and testing your reimplementation.

**Comment by dmcnaugh** [comment]
I have created the PR #72 that integrates `libtelnet` as a telnet handler to the **generic-at-modem**

_Please don't change the `LOGI()` statements to `LOGD()`_
I have made the module less chatty by changing the default local log level to `WARN` using

```
#define LOG_LOCAL_LEVEL LOG_WARN
```
To see the `INFO` messages for what is being negotiated by the telenet protocol, recompile with this option commented out or set to `LOG_INFO`. Also `libtelnet` comes with a nice telnet proxy that dumps telnet negotiation messages to the console where it is running. You will need to get the sources from the GitHub repo (above) and use `cmake` to generate the make files.

**Note:** I have only updated the `GNUmakefile`. This will need to be carried through to the platform specific makefiles.

### Telent negotiation is set to *off* by default

The following modem registers have been implemented to give user control over telnet

```
#define SREG_PORT   14  /* Default answer mode lister port - defaults to 8023 */
#define SREG_TELNET 15  /* Enable telnet protocol 1=enable, 0=disable (default) */
#define SREG_TN_SGA 16  /* Enable negotiation of SGA, default =3 (WILL & DO) */
#define SREG_TN_ECHO 17 /* Enable negotiation of ECHO, default =0 (WONT & DONT) */
#define SREG_TN_BIN 18  /* Enable negotiation of BINARY, default =0 (WONT & DONT) */
#define SREG_TN_NAWS 19 /* Enable negotiation of NAWS, default =3 (WILL & DO) */
#define SREG_COLS   20  /* Columns for NAWS, default =80 */
#define SREG_ROWS   21  /* Rows for NAWS, default =24 */
#define SREG_TN_TTYPE 22 /* Enable negotiation of TTYPE, default =3 (WILL & DO) */
```

All the `SREG_TN_*` _enable negotiation_ registers use the 2 LSBs as follows:
- bit 0: 1 = WILL, 0 = WONT
- bit 1: 1 = DO, 0 = DONT

so the most common values will be `0=WONT/DONT` and `3=WILL/DO`
but you can play with other combinations using `2=WONT/DO` and `1=WILL/DONT`

When `SREG_TN_TTYPE` is enabled it will use the value of the **environment variable** `TERM` as the string to negotiate. If `TERM` is not set in the environment and `SREG_TN_TTYPE` has bit 2 set, then a default value of `ansi` will be negotiated (this is more relevant to the ESP32 port).

So a typical session via the modem with telnet negotiation, without TTYPE will look like:
```
ATS15=1
ATS22=0
ATDtelehack.com
```

I have been testing this on the ESP32 port for a while now, but have only done limited testing today in Z80PACK. 

Feedback appreciated.

**Comment by udo-munk** [comment]
I have updated the platform specific makefiles.

**Comment by udo-munk** [comment]
I've tested the telnet modem with the PC emulation and the ESP32 port a lot. For outgoing connections it works excellent with anything I tried.

If the modem is set to answer mode and one connects with a telnet client, no telnet option negotiation seem to happen, so the telnet client works with local line editing and local echo. The modem  should send WILL DO character mode and echo, if the telnet protocol is activated, so that a client gets into the correct mode without manual intervention.

**Comment by dmcnaugh** [comment]
I'll take a look at implementing this. You are correct that right now there
is no telnet negotiation in answer mode.

**Comment by udo-munk** [comment]
Didn't do anything, it must negotiate options too. I added that with c50d6eb, and if you connect now with a telnet client to the modem in answer mode, the client works in character mode with echo from the host. With this you can now stat con:=uc1: after you made the connection, and use CP/M without odd behaviour.
I've added the negotiation without looking at the modems S registers, don't know if you really want to make this configurable, because with the wrong settings CP/M cannot be operated properly from a terminal which does local echo and local line editing.

**Comment by udo-munk** [comment]
While reading trough the stuff @ http://software.bbsdocumentary.com/AAA/AAA/CBBS/
I noticed that the modem's carrier detect signal is needed by software like this. So needs to be implemented in SIO 2B and the modem.

**Comment by dmcnaugh** [comment]
It is very simple for the modem to report CD - it is a 1:1 correlation with the TCP/IP socket being open. It already reports  a `NO CARRIER` condition when an open socket is closed by the other end.

I am less clear on how this should be represented on the SIO 2B. I've read the SIO 2 document a few times and it looks like it is via the shared command port  (port 40 dec).

Can you confirm that software like CBBS actually looks at this port?

**Comment by udo-munk** [comment]
Good, only needs to set/reset a new carrier detect variable for the SIO then too.

Correct, one bit in the SIO control port 40 dec reflects carrier detect for port B, if it was enabled before, also via port 40. I'll add this stuff to the SIO's, then it will be more clear, the manual is somewhat confusing.

I had a look at BYE5 and CBBS, one needs to provide support for carrier detect, because CP/M won't. So the programs must be configured for the type of SIO, port to use etc. Is well documented and can be implemented with the IMSAI SIO-2, in fact they did run CBBS on an IMSAI CPU later.

**Comment by udo-munk** [comment]
Added the SIO control ports with bf8b3f2, modem now must set/reset variable sio2b_cd when the carrier detect changes.

The ouput to port 40 is not for enabling/disabling carrier detect. Every SIO can be jumpered for originate and receive. If jumpered for originate the machine self can provide a carrier detect signal to the other end of the communication. They used the machine for processing through it via RS-232 including all signals, it even could provide a remote modem to another system.

**Comment by udo-munk** [comment]
Added set/reset sio2b_cd to modem when CD status changes. Now we can check via port 40 if the modem is connected or not.

**Comment by udo-munk** [comment]
Implemented, so closed.
