### ISSUE TITLE
Implement the Cromemco D+7A I/O interface card as a virtual device

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#77]
I have coded a working implementation of virtual **Cromemco D+7A I/O** interface card as I want to use this interface on the new **S-132** add-on board I am developing for the IMSAI8080esp.

The current use case is fairly trivial - it is to support a pair of **JS-1** style joysticks so that the original Cromemco software written for the Dazzler that also expects one or more JS-1 joysticks can be used (or played!).

Of course if you just compile and link the code for the virtual Cromemco D+7A I/O interface card it does nothing. The implementation depends upon the "client".

When the client is the S-132 then the data from the first 4 Analog input channels (connected to the XY pairs of the 2 analog joysticks) and the 8 bits of the Digital input channel ( 2 sets of 4 joystick buttons) are transmitted over a high speed serial UART (3Mbps) and 2 of the Analog output channels are transmitted back to the S-132 over the same link to support sound (still working on that).

I realise that I can also provide a client from the Desktop Web UI. My plan is to support 1 or 2 connected analog joysticks via the web API for game controllers and hopefully sound on the client (never tried that). This client will use web sockets for data transmission like most of the Web UI does.

The "bad" news is that the exisiting Cromemco software expects to see the D+7A I/O interface in the 8080/Z80 I/O port address space from 24-31 (decimal) 18h - 1Fh.

This is a direct clash with where I asked to put the real-time-clock (RTC) #71 

Before this module is merged into the code, the RTC will need to be moved, and the CP/M 3 Plus BIOS modified to see the RTC in its new location.

**Comment by udo-munk** [comment]
No problem, I can move the RTC away and adjust the CP/M 3 BIOS. Any idea where too already?

**Comment by dmcnaugh** [comment]
Looking through #71 you originally had the RTC at ports 65 & 66 (decimal). That seems suitable. 

Port 64 is already used by the MMU: so if there is ever another device that needs a block of 4 more ports if wont fit starting at 64 anyway.

**Comment by udo-munk** [comment]
Moved the I/O ports and build new CP/M 3 with adjusted BIOS.
