### ISSUE TITLE
Setting port values

### ISSUE THREAD

**Issue by nolash** [udo-munk/z80pack#79]
I am trying to explicitly set port values on in and out. Consider the following code:

```
main:
	IN a, (02h)
	LD a, 2ah
	OUT (03h), a
	HALT
```

What I would expect, is that when I do `p 02 => 01` in simulator before the first step, `a` should be `01` by next instruction. However trying to manipulate the port does not change anything:

```
>>> p 02
02 = ff : 01
>>> p 02
02 = ff :
```

Furthermore, I would expect that when I inspect the port value after the last instruction, it should be `2a`. However it is unchanged:

```
PC   A  SZHPNC I  IFF BC   DE   HL   A'F' B'C' D'E' H'L' IX   IY   SP
0002 ff 000001 00 00  81a0 4754 87d9 8d66 5d80 d5f1 91b0 91ad 94d7 5a40
LD	(1000),A
>>> 

PC   A  SZHPNC I  IFF BC   DE   HL   A'F' B'C' D'E' H'L' IX   IY   SP
0005 ff 000001 00 00  81a0 4754 87d9 8d66 5d80 d5f1 91b0 91ad 94d7 5a40
LD	A,02
>>> 

PC   A  SZHPNC I  IFF BC   DE   HL   A'F' B'C' D'E' H'L' IX   IY   SP
0007 02 000001 00 00  81a0 4754 87d9 8d66 5d80 d5f1 91b0 91ad 94d7 5a40
OUT	(00),A
>>> 

PC   A  SZHPNC I  IFF BC   DE   HL   A'F' B'C' D'E' H'L' IX   IY   SP
0009 02 000001 00 00  81a0 4754 87d9 8d66 5d80 d5f1 91b0 91ad 94d7 5a40
HALT
>>> p 00
00 = ff :
```

The only way I get prompted for a value input is if I change the `IN` instruction to use address `01h`:

```
main:
	IN a, (01h)
	LD a, 2ah
	OUT (03h), a
	HALT
```

That results in blocking till input from terminal:

```
>>> r inout.bin
Loader statistics for file inout.bin:
START : 0000
END   : 0009
LOADED: 000a

>>> 
a

PC   A  SZHPNC I  IFF BC   DE   HL   A'F' B'C' D'E' H'L' IX   IY   SP
0002 61 111110 00 00  cfee 20f6 32fb 307c cfea 87b9 bd1e 6e8b b0d0 5c03
LD	(1000),A
>>> 

```

No matter what I do, though, I cannot seem to find any output value that matches the `OUT`directive regardless of port.

Thanks.

**Comment by udo-munk** [comment]
The z80sim machine has only port 1 implemented for input/output to the terminal, all other ports won't do anything. See z80sim/srcsim/iosim.c.

**Comment by udo-munk** [comment]
Not an issue but correct behaviour.
