### ISSUE TITLE
USCD-P scripts should name disk images as .dsk, not .cpm?

### ISSUE THREAD

**Issue by JKjakay** [udo-munk/z80pack#81]
Thank you for your interesting emulation package! I like the old CP/M systems and have successfully started the standard CP/M versions. However, I failed to run the USCD-P images. Then I noticed that the scripts would determine disk endings as "*.cpm", and apparently cpmsim wont recognize them in this case. If this is changed to "*.dsk", the USCD-P images are recognized and start up fine (Tested on 1.37).

Kind Regards

By the way, I would really appreciate it if there were a "Quick Start" introduction for Cromemco, Altair and such, too. I have yet to understand how to set up those.

**Comment by udo-munk** [comment]
You are welcome. At some time the filename extension was renamed from .cpm to .dsk, but I never found the time
to modify all scripts and upload packages again, so there might still be some with this issue.

For the systems with front panel you first need to build the front panel library. This depends on some X11 and OpenGL
libraries which need to be installed on the system. It is different on every system which packages needs to be installed,
so there is no “Quick Start” for this. Try building the front panel library and if the compiler complains about a missing
include file or library file lookup what package provides it on the OS you are using.

Best regards,
Udo

**Comment by udo-munk** [comment]
Is not an issue here.
