### ISSUE TITLE
MacOS 11.4 Dual-Core Intel Core i5:  system: Op-code trap at 1d42 dd 84

### ISSUE THREAD

**Issue by ravn** [udo-munk/z80pack#83]
I am kicking the tires of z80pack 1.37 just to see how much faster than RunCPM it is.

For this purpose I run the zexdoc.com command (which on my machine takes a minute with RunCPM).  It fails with the following output:

```
B>zexdoc
Z80doc instruction exerciser
<adc,sbc> hl,<bc,de,hl,sp>....  OK
add hl,<bc,de,hl,sp>..........  OK
add ix,<bc,de,ix,sp>..........  OK
add iy,<bc,de,iy,sp>..........  OK
aluop a,nn....................  OK
aluop a,<b,c,d,e,h,l,(hl),a>..  OK
aluop a,<ixh,ixl,iyh,iyl>.....E (20985954) system: Op-code trap at 1d42 dd 84
```

For what it's worth, this also happens with zexall.doc where the crc's fail:

```
B>zexall
Z80all instruction exerciser
<adc,sbc> hl,<bc,de,hl,sp>....  ERROR **** crc expected:d48ad519 found:f39089a0
add hl,<bc,de,hl,sp>..........  ERROR **** crc expected:d9a4ca05 found:1165fc90
add ix,<bc,de,ix,sp>..........  ERROR **** crc expected:b1df8ec0 found:c359f7a2
add iy,<bc,de,iy,sp>..........  ERROR **** crc expected:39c8589b found:5fc828e9
aluop a,nn....................  ERROR **** crc expected:51c19c2e found:48799360
aluop a,<b,c,d,e,h,l,(hl),a>..  ERROR **** crc expected:06c7aa8e found:fe43b016
aluop a,<ixh,ixl,iyh,iyl>.....E (21348397) system: Op-code trap at 1d42 dd 84
````

Thanks

**Comment by udo-munk** [comment]
z80pack doesn’t emulate all undocumented op-codes, only these used by existing software. Also it doesn’t
emulate the undocumented bits in the flag register. The programs from Frank Cringel have assembler options
to build them so that not any undocumented behaviour of the CPU is exercised. z80pack already includes
a disk image with the programs, with the conditional assembly set appropriate. Use this version on all
machines for comparing.

Regards,
Udo

**Comment by ravn** [comment]
Ok.

To my understanding the zexdoc only exercises documented opcodes, hence the issue.

The question was more if this was a MacOS specific bug or not.  It appears that it works as expected.

Thanks.

**Comment by udo-munk** [comment]
It only execises documented opcodes, but one also needs to disable calculation of the undocumented flag bits, which are not emulated by z80pack, because they cannot be used for anything.
Not an issue on any platform but expected behaviour.
